version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:8'
    working_directory: ~/repo
    steps:
      - run:
          name: Install node@v14.16.0
          command: |
            load-nvm.sh
            nvm install v14.16.0
            nvm alias default v14.16.0
            npm version
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run:
          name: 'Install dependencies'
          command: |
            npm version
            npm install
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run:
          name: 'Run Unit Tests'
          command: 'npm run test'
      - run:
          name: 'Deploy to Firebase Hosting'
          command: 'npm run deploy'
branches:
  only:
    - develop
