version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:8'
    working_directory: ~/repo
    steps:
      - run:
          name: Install Node v14.16.0
          command: |
            set +e
            wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm install v14.16.0
            nvm alias default 14.16.0

            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: "npm install"
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run:
          name: 'Build Project'
          command: 'npm run build'
      - run:
          name: 'Deploy to Firebase Hosting'
          command: 'firebase deploy --token=$FIREBASE_TOKEN
branches:
  only:
    - develop
